edition = "2024"
style_edition = "2024"

comment_width = 100
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
max_width = 100
normalize_comments = true
unstable_features = true
wrap_comments = true
